const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'../..');
const evaluate=(text,name)=>{const m=text.match(new RegExp('const '+name+' = (\\[[\\s\\S]*?\\n\\s*\\]);'));if(!m)return null;return JSON.parse(JSON.stringify(vm.runInNewContext(m[1].replaceAll("rectangle's","rectangle\\'s"),{}, {timeout:1000})));};
const modules=[];const types={};
for(let id=1;id<=7;id++){
 const html=fs.readFileSync(path.join(root,`module-${id}-simple.html`),'utf8');const name=html.match(/<title>Module \d+: (.*?)(?: - Reckoning Figures)?<\/title>/)[1];
 let figures=evaluate(html,'figures');if(!figures){figures=[...html.matchAll(/class="figure-card" id="figure-(\d+)"[\s\S]*?class="figure-title">([^<]+)</g)].map(m=>({num:Number(m[1]),title:m[2],file:`figure-${m[1]}.html`}));}
 const lessons=figures.map(f=>{const file=path.join(root,f.file),lesson={id:Number(f.num),title:f.title,source:f.file};if(!fs.existsSync(file))return {...lesson,available:false,questions:[]};const text=fs.readFileSync(file,'utf8');let items=evaluate(text,'problems'),format='problems';if(!items){items=evaluate(text,'content');format='content';}if(!items)throw Error('No content '+f.file);
 const questions=items.map(item=>{let q={...item};if(format==='content'){
 if(item.mode==='tutorial'||item.type==='walkthrough')q={...item,type:'tutorial',q:item.title,eq:''};
 else if(item.mode==='interactive')q={...item,type:'graph',q:item.question,eq:item.inequality,answer:item.correctAnswer};
 else {if(!item.choices){console.log(f.file,item);throw Error('unknown')}q.type='multiple-choice';q.q=item.q||item.question;q.eq=item.eq||'';if(typeof item.choices[0]==='object'){q.answer=item.choices.findIndex(c=>c.correct);q.choices=item.choices.map(c=>c.text);}else q.answer=item.choices.indexOf(item.answer);if(q.answer<0)throw Error('Unmatched answer '+f.file);}
 }if(!q.type){q.type='multiple-choice';q.answer=q.choices.indexOf(q.answer);}types[q.type]=(types[q.type]||0)+1;return q;});
 return {...lesson,available:true,premium:/function checkPremiumAccess/.test(text)||/function checkPremiumAccess/.test(html),questions,original:items};});modules.push({id,name,lessons});
}
fs.writeFileSync(path.join(root,'preview/course.js'),'// Generated by scripts/import-course.cjs; original lesson objects retained for parity checks.\nexport const course = '+JSON.stringify(modules,null,2)+';\n');console.log(JSON.stringify({modules:modules.map(m=>({name:m.name,lessons:m.lessons.length,missing:m.lessons.filter(l=>!l.available).map(l=>l.id)})),types},null,2));
