import {readFileSync} from 'node:fs';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,getDocs,collection,query,where,updateDoc,deleteDoc,serverTimestamp,Timestamp} from 'firebase/firestore';
import {course} from '../../preview/course.js';
import {classroomAPI} from '../../preview/school/classroom-api.js';
const env=await initializeTestEnvironment({projectId:'demo-reckoning-owner',firestore:{host:'127.0.0.1',port:8085,rules:readFileSync('firebase/owner-test.rules','utf8')}});
const db=uid=>env.authenticatedContext(uid).firestore(),teacher=db('teacher'),student=db('student'),other=db('other'),admin=db('admin');
const base=['schools','a','classes','class1'];
const classData=(uid='teacher')=>({name:'Algebra',teacherUid:uid,createdBy:'teacher',createdAt:serverTimestamp()});
const assignment=()=>({title:'Practice',instructions:'Take your time',lessonIds:[1],due:'2026-12-01',createdBy:'teacher',createdAt:serverTimestamp()});
const result=()=>({uid:'student',lessonId:1,questions:course[0].lessons[0].questions.filter(q=>q.type!=='tutorial').length,firstTry:2,supportSteps:1,seconds:60,sessionId:'session1',completedAt:serverTimestamp()});
const enroll=(uid='student')=>setDoc(doc(teacher,...base,'students',uid),{label:'Test student',addedAt:serverTimestamp()});
try{
 await env.clearFirestore();await env.withSecurityRulesDisabled(async context=>{const d=context.firestore();for(const school of ['a','b']){await setDoc(doc(d,'schools',school),{name:school,status:'pilot',license:{startsOn:Timestamp.fromMillis(Date.now()-86400000),endsOn:Timestamp.fromMillis(Date.now()+86400000),courses:['algebra1']}});for(const [uid,role] of [['teacher','teacher'],['teacher2','teacher'],['student','student'],['other','student'],['admin','administrator']])await setDoc(doc(d,'schools',school,'members',uid),{role,state:'active'});}});
 await assertSucceeds(setDoc(doc(teacher,...base),classData()));
 await assertFails(setDoc(doc(student,'schools','a','classes','spoof'),{...classData(),createdBy:'student'}));
 await assertFails(setDoc(doc(teacher,'schools','a','classes','spoof'),classData('teacher2')));
 await assertSucceeds(getDocs(query(collection(teacher,'schools','a','classes'),where('teacherUid','==','teacher'))));
 await assertFails(getDocs(collection(teacher,'schools','a','classes')));
 await assertFails(getDoc(doc(db('teacher2'),...base)));
 await assertFails(getDoc(doc(student,...base)));
 await assertFails(enroll('teacher2'));
 await assertFails(enroll('unknown'));
 await assertSucceeds(enroll());await assertSucceeds(getDoc(doc(student,...base)));
 await assertFails(getDocs(collection(student,...base,'students')));
 await assertFails(setDoc(doc(student,...base,'students','other'),{label:'Other',addedAt:serverTimestamp()}));
 await assertSucceeds(setDoc(doc(teacher,...base,'assignments','hw'),assignment()));
 await assertFails(setDoc(doc(db('teacher2'),...base,'assignments','spoof'),{...assignment(),createdBy:'teacher2'}));
 await assertFails(setDoc(doc(teacher,...base,'assignments','missing'),{...assignment(),lessonIds:[9999]}));
 const premium=course.flatMap(u=>u.lessons).find(l=>l.premium);if(premium)await assertFails(setDoc(doc(teacher,...base,'assignments','premium'),{...assignment(),lessonIds:[premium.id]}));
 await assertFails(setDoc(doc(teacher,...base,'assignments','duplicate'),{...assignment(),lessonIds:[1,1]}));
 await assertFails(getDoc(doc(other,...base,'assignments','hw')));
 await assertSucceeds(getDocs(collection(student,...base,'assignments')));
 const r=doc(student,...base,'assignments','hw','results','student_1');
 await assertFails(setDoc(r,{...result(),firstTry:1000}));
 await assertFails(setDoc(r,{...result(),questions:999}));
 await assertFails(setDoc(r,{...result(),uid:'other'}));
 await assertFails(setDoc(doc(student,...base,'assignments','hw','results','student_2'),{...result(),lessonId:2}));
 await assertFails(setDoc(doc(student,...base,'assignments','hw','results','alternate'),result()));
 await assertSucceeds(setDoc(r,result()));await assertFails(setDoc(r,result()));await assertFails(deleteDoc(r));
 await assertSucceeds(getDocs(query(collection(student,...base,'assignments','hw','results'),where('uid','==','student'))));
 await assertFails(getDocs(collection(student,...base,'assignments','hw','results')));
 await assertSucceeds(enroll('other'));
 await assertFails(getDoc(doc(other,...base,'assignments','hw','results','student_1')));
 await assertSucceeds(getDocs(collection(teacher,...base,'assignments','hw','results')));
 // Exercise production API, including first completion and duplicate retries.
 const api=classroomAPI(student,{currentUser:{uid:'student'}});
 await assertSucceeds(api.submit('a','class1','hw',{lessonId:1,questions:result().questions,firstTry:0,supportSteps:0,seconds:1,sessionId:'retry'}));
 if((await getDoc(r)).data().firstTry!==2)throw Error('Retry overwrote first result');
 await assertSucceeds(setDoc(doc(teacher,...base,'assignments','hw2'),assignment()));
 const payload={lessonId:1,questions:result().questions,firstTry:1,supportSteps:0,seconds:10,sessionId:'new'};
 await assertSucceeds(api.submit('a','class1','hw2',payload));
 await assertSucceeds(api.submit('a','class1','hw2',payload));
 if((await getDocs(collection(teacher,...base,'assignments','hw2','results'))).size!==1)throw Error('Duplicate completion');
 await assertSucceeds(deleteDoc(doc(teacher,...base,'students','student')));
 await assertFails(getDoc(doc(student,...base,'assignments','hw')));
 await assertFails(api.submit('a','class1','hw2',payload));
 await assertSucceeds(enroll());
 await env.withSecurityRulesDisabled(ctx=>updateDoc(doc(ctx.firestore(),'schools','a','members','student'),{state:'removed'}));
 await assertFails(getDoc(doc(student,...base)));
 await env.withSecurityRulesDisabled(ctx=>updateDoc(doc(ctx.firestore(),'schools','a','members','student'),{state:'active'}));
 await env.withSecurityRulesDisabled(ctx=>updateDoc(doc(ctx.firestore(),'schools','a'),{status:'paused'}));
 await assertFails(setDoc(doc(teacher,...base,'assignments','paused'),assignment()));
 await assertFails(setDoc(doc(other,...base,'assignments','hw','results','other_1'),{...result(),uid:'other'}));
 await assertSucceeds(getDoc(doc(student,...base,'assignments','hw'))); // history retained
 await assertSucceeds(getDocs(collection(admin,...base,'assignments','hw','results')));
 await env.withSecurityRulesDisabled(ctx=>updateDoc(doc(ctx.firestore(),'schools','a','members','teacher'),{state:'removed'}));
 await assertFails(getDocs(collection(teacher,...base,'assignments','hw','results')));
 await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),...base)));
 console.log('PASS connected class ownership, student enrollment, curriculum restrictions, private results, API retries, immutable completions, license pause and revocation');
}finally{await env.cleanup();}
