let clientPromise;
export const getClient=()=>clientPromise||(clientPromise=import('./vendor/firebase.js'));
export function showAccount(dialog,{user,status,onSync,onImport}){
 const content=dialog.querySelector('#dialog-body');content.innerHTML='<div class="account"><span class="eyebrow">YOUR PROGRESS</span><h2>Keep your momentum.</h2><p class="account-status" role="status"></p><div class="account-body"></div></div>';
 const message=content.querySelector('.account-status');message.textContent=user?`Signed in as ${user.email}. ${status}`:'Play as a guest, or sign in to keep progress across devices.';
 const body=content.querySelector('.account-body');
 const run=async action=>{body.querySelectorAll('button').forEach(b=>b.disabled=true);try{await action();}catch(error){message.textContent=error.code==='permission-denied'?'Cloud access was denied. Progress is saved here; the Firebase progress rules need to be configured.':error.code?.startsWith('auth/')?'Could not complete the account request. Check your details and connection, then try again.':error.message||'Could not connect. Your local progress is safe.';}finally{body.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 if(user){body.innerHTML='<button class="primary" id="sync-now">Sync now</button><button class="subtle" id="import-guest">Copy this device’s guest progress into my account</button><button class="subtle" id="sign-out">Sign out</button><p class="account-note">Guest and account saves are separate. Cloud sync covers lessons, XP, and activity days. Premium access is not changed by signing in.</p>';body.querySelector('#sync-now').onclick=()=>run(async()=>{await onSync();message.textContent='Progress synced.';});body.querySelector('#import-guest').onclick=()=>run(async()=>{onImport();await onSync();message.textContent='Guest progress copied and synced.';});body.querySelector('#sign-out').onclick=()=>run(async()=>{await(await getClient()).logout();});}
 else{body.innerHTML='<form><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="current-password" minlength="6" required></label><button class="primary" type="submit">Sign in</button><button class="subtle" type="button" id="register">Create an account</button><button class="subtle" type="button" id="reset-password">Reset password</button></form><p class="account-note">Guest mode works without an account. Account email and progress are sent to the existing Reckoning Figures Firebase project. Guest progress is copied only when you choose to import it after signing in.</p>';const form=body.querySelector('form');const credentials=()=>[form.elements.email.value.trim(),form.elements.password.value];form.onsubmit=e=>{e.preventDefault();run(async()=>{await(await getClient()).login(...credentials());});};body.querySelector('#register').onclick=()=>{if(form.reportValidity())run(async()=>{await(await getClient()).register(...credentials());});};body.querySelector('#reset-password').onclick=()=>{if(form.elements.email.reportValidity())run(async()=>{await(await getClient()).reset(credentials()[0]);message.textContent='If this account exists, check your email for a reset link.';});};}
 dialog.showModal();
}
