import { bolt, energyIcon } from './brand-art.js';
const KEY='rfLearningPlanV1';
let memoryPlan=null;
export function learningPlan(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||memoryPlan;}catch{return memoryPlan;}}
export function needsWelcome(progress){return !learningPlan()&&!(progress.xp>0||progress.sessions>0||progress.completed||progress.completedLessons?.length);}
const confidenceOptions=[['new','A fresh start','I’m new to algebra, or it feels confusing.'],['building','Build my confidence','I know some basics. I want more practice.'],['review','Sharpen my skills','I’m reviewing Algebra 1 and ready for a challenge.']];
const goalOptions=[[5,'Small spark','A little room for learning.'],[10,'Steady charge','Time to build a rhythm.'],[15,'Extra energy','A longer practice session.']];
export function showOnboarding(app,{onFinish}){
 const saved=learningPlan();let step=0,confidence=confidenceOptions.some(x=>x[0]===saved?.confidence)?saved.confidence:null,minutes=goalOptions.some(x=>x[0]===saved?.minutes)?saved.minutes:null,finished=false;
 function finish(action){if(finished)return;finished=true;memoryPlan={version:1,confidence:confidence||'building',minutes:minutes||5,completed:true};try{localStorage.setItem(KEY,JSON.stringify(memoryPlan));}catch{}onFinish(action);}
 function render(animate=true){
  const selected=step===1?confidence:minutes;
  const titles=['Find your spark.','Where are you starting?','Make room for a little progress.','Your next chapter starts here.'];
  const descriptions=['Algebra can click. Build confidence one figure at a time, from your first equation to Algebra 1 challenges.','No test. No pressure. Just tell us how algebra feels right now.','Choose a daily practice intention. You can change it anytime.',''];
  const content=step===0?`<div class="welcome-art" aria-hidden="true"><div class="welcome-orbit"></div><div class="welcome-orbit orbit-tilt"></div>${bolt('object')}<span class="welcome-equation eq-left">x + 3</span><span class="welcome-equation eq-right">= 7</span><span class="welcome-spark">✦</span></div><span class="eyebrow">YOUR ALGEBRA ADVENTURE</span>`:step===1?`<div class="onboarding-symbol">${energyIcon('crystal','medium')}</div>`:step===2?`<div class="onboarding-symbol">${energyIcon('flame','medium')}</div>`:`<div class="welcome-art welcome-ready" aria-hidden="true"><div class="welcome-orbit"></div>${bolt('object')}</div><span class="eyebrow">A LITTLE PRACTICE. REAL PROGRESS.</span>`;
  const options=step===1?confidenceOptions.map(([value,label,copy],i)=>`<button class="onboarding-option ${confidence===value?'is-selected':''}" data-value="${value}" aria-pressed="${confidence===value}"><span class="option-mark" aria-hidden="true">${['x','x²','√x'][i]}</span><span><strong>${label}</strong><small>${copy}</small></span><span class="option-check" aria-hidden="true">${confidence===value?'✓':'○'}</span></button>`).join(''):step===2?goalOptions.map(([value,label,copy])=>`<button class="onboarding-option ${minutes===value?'is-selected':''}" data-value="${value}" aria-pressed="${minutes===value}"><span class="option-minutes">${value}<small>min/day</small></span><span><strong>${label}</strong><small>${copy}</small></span><span class="option-check" aria-hidden="true">${minutes===value?'✓':'○'}</span></button>`).join(''):'';
  app.innerHTML=`<main class="onboarding"><header class="onboarding-header"><a class="onboarding-brand" href="#" aria-label="Reckoning Figures">${bolt()}<span>Reckoning Figures</span></a><button class="onboarding-skip">Skip for now</button></header><nav class="onboarding-progress" aria-label="Setup progress">${titles.map((_,i)=>`<span class="${i<=step?'is-filled':''}" ${i===step?'aria-current="step"':''}><span class="sr-only">Step ${i+1}${i===step?', current':''}</span></span>`).join('')}</nav><section class="onboarding-content onboarding-step-${step}" ${animate?'':'style="animation:none"'}>${content}<h1 tabindex="-1">${titles[step]}</h1>${descriptions[step]?`<p class="onboarding-description">${descriptions[step]}</p>`:''}${step===0?`<div class="welcome-benefits"><span>✓ Short lessons</span><span>✓ Learn from mistakes</span><span>✓ Celebrate your progress</span></div>`:step<3?`<div class="onboarding-options" role="group" aria-label="${step===1?'Algebra confidence':'Daily practice intention'}">${options}</div>${step===2?'<p class="onboarding-note">A goal, not a timer. No reminders or notifications are turned on.</p>':''}`:`<div class="onboarding-plan"><span>Your daily intention</span><strong>${minutes} minutes. One step forward.</strong><p>${confidence==='new'?'Start with a simple equation. Hints and retries are there whenever you need them.':confidence==='review'?'Start with a warm-up, or explore the course to choose a figure you want to revisit.':'Turn what you know into confidence. Start with a warm-up and build from there.'}</p></div><p class="onboarding-note">Your plan is saved on this device. No account needed to start.</p>`}</section><footer class="onboarding-footer"><button class="primary onboarding-next" ${step>0&&step<3&&!selected?'disabled':''}>${step===0?'Let’s get started →':step===3?'Start my first figure →':'Continue →'}</button>${step===0?'<button class="onboarding-explore">Already learning? Open my path</button>':step===3?'<button class="onboarding-explore">Explore the course instead</button>':'<button class="onboarding-back">← Back</button>'}</footer></main>`;
  app.querySelector('.onboarding-brand').onclick=e=>{e.preventDefault();step=0;render();};
  app.querySelector('.onboarding-skip').onclick=()=>finish('home');
  app.querySelector('.onboarding-next').onclick=()=>{if(step===3)finish('lesson');else{step++;render();}};
  app.querySelector('.onboarding-explore')?.addEventListener('click',()=>finish('home'));
  app.querySelector('.onboarding-back')?.addEventListener('click',()=>{step--;render();});
  app.querySelectorAll('[data-value]').forEach(button=>button.onclick=()=>{if(step===1)confidence=button.dataset.value;else minutes=Number(button.dataset.value);render(false);app.querySelector(`[data-value="${button.dataset.value}"]`).focus({preventScroll:true});});
  app.querySelector('h1').focus({preventScroll:true});window.scrollTo(0,0);
 }
 render();
}
