import {course} from '../course.js';
import {STORAGE_KEY,seed,dayKey,daysAgo,scopedLearners,scopedAttempts,metrics,learnerStatus,assignmentProgress,addClass,addAssignment,csv} from './model.js?v=09cc560f7c2f';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={curriculum:'M3 3h7l2 3 2-3h7v17h-7l-2 2-2-2H3zM12 6v16',overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',classes:'M3 6h18v15H3zM7 3v6M17 3v6M3 11h18',learners:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M1 22v-3a7 7 0 0 1 14 0v3M17 4a4 4 0 0 1 0 8M18 15a6 6 0 0 1 5 6',assignments:'M6 4h12v18H6zM9 2h6v4H9zM9 10h6M9 14h6M9 18h3',reports:'M3 3v18h18M7 17v-5M12 17V8M17 17V4',support:'M4 13v-2a8 8 0 0 1 16 0v2M4 12H2v6h4v-6zM20 12h2v6h-4v-6zM20 18q0 4-8 4',arrow:'M5 12h14M13 6l6 6-6 6',download:'M12 2v13M6 9l6 6 6-6M3 16v6h18v-6',plus:'M12 4v16M4 12h16'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${`<path d="${paths[name]||paths.overview}"/>`}</svg>`;
let data,storageOK=true;try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');data=saved?.version===1&&['classes','learners','attempts','assignments','support'].every(k=>Array.isArray(saved[k]))?saved:seed();}catch{data=seed();storageOK=false;}
let tab='overview',classId='all',days=7,search='';const lessonMap=new Map(course.flatMap(m=>m.lessons).map(l=>[l.id,l]));const available=course.flatMap(m=>m.lessons).filter(l=>l.available&&!l.premium);
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));storageOK=true;}catch{storageOK=false;notice('Storage unavailable. Changes will last for this visit only.');}}save();
function notice(message){$('#toast').textContent=message;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#toast').textContent='',5000);}
function className(id){return data.classes.find(c=>c.id===id)?.name||'Unknown class';}
function dateLabel(key){return new Date(key+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function pct(n){return n===null?'—':n+'%';}
function button(label,action,primary=false,ico='plus'){return `<button class="org-button ${primary?'org-primary':''}" data-action="${action}">${icon(ico)}${label}</button>`;}
function empty(title,copy){return `<div class="org-empty"><strong>${title}</strong><p>${copy}</p></div>`;}
function rows(learners,attempts){return learners.map(l=>{const a=attempts.filter(a=>a.learnerId===l.id),m=metrics(a),status=learnerStatus(a);return `<tr><td><button class="learner-link" data-learner="${l.id}"><span class="learner-avatar">${escape(l.name.slice(0,1))}</span><span>${escape(l.name)}<small>${escape(className(l.classId))}</small></span></button></td><td>${m.sessions}</td><td>${pct(m.accuracy)}</td><td><span class="org-status ${status==='Check in'?'status-check':status==='Practicing'?'status-good':''}">${status}</span></td><td><button class="row-open" data-learner="${l.id}" aria-label="View ${escape(l.name)}">${icon('arrow')}</button></td></tr>`}).join('');}
function learnerTable(learners,attempts){return learners.length?`<div class="table-scroll"><table><thead><tr><th>Learner</th><th>Lessons completed</th><th>First-try accuracy</th><th>Practice signal</th><th><span class="sr-only">Details</span></th></tr></thead><tbody>${rows(learners,attempts)}</tbody></table></div>`:empty('No learners here yet','Add demo learners from Classes to try the workflow.');}
function chart(attempts){const n=days||30,windowDays=Math.min(n,30),keys=Array.from({length:windowDays},(_,i)=>daysAgo(windowDays-1-i)),counts=keys.map(d=>attempts.filter(a=>a.date===d).length),max=Math.max(...counts,1);return `<div class="org-bars" role="img" aria-label="Completed lessons by day: ${keys.map((k,i)=>dateLabel(k)+': '+counts[i]).join('; ')}">${keys.map((k,i)=>`<div title="${dateLabel(k)}: ${counts[i]} lessons"><b>${counts[i]||''}</b><i style="height:${counts[i]/max*110}px"></i><small>${keys.length<=7?new Date(k+'T12:00').toLocaleDateString(undefined,{weekday:'short'}):i%7===0?new Date(k+'T12:00').getDate():''}</small></div>`).join('')}</div>`;}
function assignmentCards(){const list=data.assignments.filter(a=>classId==='all'||a.classId===classId);return list.length?list.map(a=>{const result=assignmentProgress(data,a),done=result.filter(r=>r.done).length;return `<article class="assignment-card"><div class="assignment-mark">${icon('assignments')}</div><div><span class="org-kicker">${escape(className(a.classId))}</span><h3>${escape(a.title)}</h3><p>${a.mode==='homework'?'Homework practice · ':''}${a.lessonIds.length} figures · Due ${dateLabel(a.due)}${a.due<dayKey()?' · Past due':''}</p><div class="org-meter"><i style="width:${done/Math.max(1,result.length)*100}%"></i></div><small>${done} of ${result.length} learners completed all assigned figures</small></div><button class="org-button" data-assignment="${a.id}">View assignment ${icon('arrow')}</button></article>`}).join(''):empty('A clear next step starts here','Create a demo assignment for a class to see completion tracking.');}
function render(){
 const learners=scopedLearners(data,classId),attempts=scopedAttempts(data,classId,days),m=metrics(attempts),attention=learners.filter(l=>learnerStatus(attempts.filter(a=>a.learnerId===l.id))!=='Practicing');
 const titles={curriculum:'See what comes next. Teach with purpose.',overview:'See the progress. Find the next step.',classes:'A home for every learning group.',learners:'Know who needs a little support.',assignments:'Give practice a clear direction.',reports:'Turn practice into useful insight.',support:'Keep your program moving.'};
 $('#workspace').innerHTML=`<div class="org-shell"><aside class="org-sidebar"><a class="org-brand" href="../index.html"><img src="../assets/brand-transparent.png" alt=""><span>Reckoning Figures<small>EDUCATOR WORKSPACE</small></span></a><span class="workspace-name">The Spark Lab <small>Demo organization</small></span><nav aria-label="Workspace navigation">${Object.keys(titles).map(k=>`<button data-tab="${k}" class="${tab===k?'active':''}" ${tab===k?'aria-current="page"':''}>${icon(k)}${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</nav><a class="student-preview" href="../index.html">${icon('arrow')} Open learner experience</a><div class="org-sidebar-note">Built for the moments<br>when algebra finally clicks.</div></aside><main class="org-main"><div class="org-demo-banner"><span><b>Interactive demo</b> · Sample learners. Changes stay in this browser. Do not enter real student information.</span><button data-action="reset">Reset demo</button></div>${!storageOK?'<p class="org-storage">Browser storage is unavailable. Changes last for this visit only.</p>':''}<header class="org-heading"><div><span class="org-kicker">${tab==='overview'?'YOUR TEACHING, WITH A LITTLE MORE CLARITY':tab.toUpperCase()}</span><h1 tabindex="-1">${titles[tab]}</h1></div>${tab==='classes'?button('Create class','class',true):tab==='support'?button('Draft support request','support',true):button('Create assignment','assignment',true)}</header>${tab!=='support'?`<div class="org-filters"><label>Class <select id="class-filter"><option value="all">All classes</option>${data.classes.map(c=>`<option value="${c.id}" ${classId===c.id?'selected':''}>${escape(c.name)}</option>`).join('')}</select></label>${['overview','learners','reports'].includes(tab)?`<label>Reporting period <select id="period-filter"><option value="7" ${days===7?'selected':''}>Last 7 days</option><option value="30" ${days===30?'selected':''}>Last 30 days</option><option value="0" ${days===0?'selected':''}>All time</option></select></label>`:''}<span class="filter-note">${learners.length} demo learners${tab==='assignments'?' · Completion since assignment date':''}</span></div>`:''}<div id="org-content"></div><footer class="org-footer">Reckoning Figures for organizations · Demo workspace</footer></main></div>`;
 let content='';
 if(tab==='curriculum')content=curriculumView();
 else
 if(tab==='overview'||tab==='reports'){
 content=`<section class="org-stats" aria-label="Practice summary"><article><span>Active learners</span><strong>${m.active}<small> / ${learners.length}</small></strong><p>Completed at least one lesson</p></article><article><span>Lessons completed</span><strong>${m.sessions}</strong><p>Includes repeat practice</p></article><article><span>First-try accuracy</span><strong>${pct(m.accuracy)}</strong><p>Across ${m.questions} scored questions</p></article><article><span>Practice time</span><strong>${m.minutes}<small> min</small></strong><p>Completed sessions only</p></article></section><div class="org-two-column"><section class="org-panel"><div class="panel-title"><h2>Practice rhythm</h2><span>${days===0?'Latest 30 days':`Last ${days} days`}</span></div>${chart(attempts)}<p class="panel-note">Completed lessons per day. A repeat lesson counts as another practice session.</p></section><section class="org-panel focus-panel"><span class="org-kicker">A GOOD PLACE TO START</span><h2>${attention.length?`${attention.length} learners to check in with`:'Everyone has been practicing'}</h2><p>${attention.length?'Some learners have no completed practice in this period or first-try accuracy below 70%. Open their details before deciding what support they need.':'Keep the rhythm going with a new practice assignment.'}</p><button class="org-button" data-tab="learners">View learners ${icon('arrow')}</button></section></div>`;
 if(tab==='overview')content+=`<section class="org-panel"><div class="panel-title"><h2>Where a check-in could help</h2><button class="org-text-button" data-tab="learners">All learners →</button></div>${attention.length?learnerTable(attention.slice(0,5),attempts):empty('No check-in flags in this period','Use Reports to review practice by figure.')}</section>`;
 else{const lessons=[...new Set(attempts.map(a=>a.lessonId))];content+=`<section class="org-panel"><div class="panel-title"><div><h2>Practice by figure</h2><p class="panel-note">Practice accuracy is not a mastery score or a measure of learning gain.</p></div>${button('Export learner CSV','export',false,'download')}</div>${lessons.length?`<div class="table-scroll"><table><thead><tr><th>Figure</th><th>Sessions</th><th>First-try accuracy</th><th>Questions</th></tr></thead><tbody>${lessons.map(id=>{const n=metrics(attempts.filter(a=>a.lessonId===id));return `<tr><td>${escape(lessonMap.get(id)?.title||'Figure '+id)}</td><td>${n.sessions}</td><td>${pct(n.accuracy)}</td><td>${n.questions}</td></tr>`}).join('')}</tbody></table></div>`:empty('No completed practice in this period','Try another class or reporting period.')}</section><details class="org-panel metric-notes"><summary>How these reports are calculated</summary><p>Accuracy = questions answered correctly on the first try ÷ scored questions across completed sessions. Results are weighted by question count. Active means at least one completed session in the selected period. No practice is shown as “—”, never 0% accuracy. Assignment completion uses sessions on or after the assignment date, regardless of the report filter. These sample records do not establish educational outcomes.</p></details>`;}
 }else if(tab==='classes')content=`<div class="class-grid">${data.classes.filter(c=>classId==='all'||c.id===classId).map(c=>`<article class="org-panel class-card"><div class="class-art">${icon('classes')}<span>${scopedLearners(data,c.id).length} learners</span></div><h2>${escape(c.name)}</h2><p>${escape(c.description||'A new group, ready to begin.')}</p><small>${escape(c.instructor)}</small><div class="class-actions"><button class="org-button" data-class="${c.id}">Open roster ${icon('arrow')}</button><button class="org-text-button" data-add-learner="${c.id}">Add demo learner</button></div></article>`).join('')}</div>`;
 else if(tab==='learners')content=`<section class="org-panel"><div class="panel-title"><h2>Class roster</h2><label class="search-label"><span class="sr-only">Search learner names</span><input id="learner-search" placeholder="Search learners" value="${escape(search)}"></label></div><div id="roster-results">${learnerTable(learners.filter(l=>l.name.toLowerCase().includes(search.toLowerCase())),attempts)}</div><p class="panel-note">“Check in” is a conversation starter based on practice accuracy, not a diagnosis or student label.</p></section>`;
 else if(tab==='assignments')content=`<p class="section-note">Demo assignments are saved here. Delivery to student accounts becomes available after organization accounts are connected.</p><div class="assignment-list">${assignmentCards()}</div>`;
 else content=`<div class="org-two-column"><section class="org-panel"><span class="org-kicker">PILOT LAUNCH GUIDE</span><h2>Start small. Learn together.</h2><ol class="support-steps"><li><strong>Create a class</strong><p>Use Classes to organize a learning group and try adding sample learners.</p></li><li><strong>Choose the next figure</strong><p>Create an assignment with a due date and one or more available lessons.</p></li><li><strong>Review practice, then talk</strong><p>Use the same reporting period each week. Ask learners what felt easier and where they got stuck.</p></li></ol></section><section class="org-panel"><h2>Help with the workspace</h2><details><summary>Why are the learners marked as demo?</summary><p>This workspace uses fictional sample records. Live rosters and student results require secure organization accounts.</p></details><details><summary>Does an assignment notify students?</summary><p>Not in this demo. You can save and review an assignment here, but it is not delivered or emailed.</p></details><details><summary>What does first-try accuracy mean?</summary><p>It shows how many questions were answered correctly on the first attempt across completed sessions. It does not measure improvement on its own.</p></details><details><summary>Where does a support request go?</summary><p>Requests are saved as local drafts. Download a draft to share it through your own support channel. No message is sent from this demo.</p></details></section></div><section class="org-panel"><div class="panel-title"><h2>Support drafts</h2><span>Saved here · Not submitted</span></div>${data.support.length?data.support.map(t=>`<article class="support-draft"><div><strong>${escape(t.subject)}</strong><p>${escape(t.category)} · ${dateLabel(t.date)} · Draft</p></div><button class="org-button" data-ticket="${t.id}">${icon('download')} Download draft</button></article>`).join(''):empty('Keep a question or issue together','Draft a request with the steps you tried. Leave out student names and personal information.')}</section>`;
 $('#org-content').innerHTML=content;bind();
}
function bind(){
 bindCurriculum();
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;search='';render();$('h1').focus({preventScroll:true});window.scrollTo(0,0)});
 $('#class-filter')?.addEventListener('change',e=>{classId=e.target.value;render()});$('#period-filter')?.addEventListener('change',e=>{days=Number(e.target.value);render()});
 document.querySelectorAll('[data-learner]').forEach(b=>b.onclick=()=>learnerDetail(b.dataset.learner));
 $('#learner-search')?.addEventListener('input',e=>{search=e.target.value;$('#roster-results').innerHTML=learnerTable(scopedLearners(data,classId).filter(l=>l.name.toLowerCase().includes(search.toLowerCase())),scopedAttempts(data,classId,days));$('#roster-results').querySelectorAll('[data-learner]').forEach(b=>b.onclick=()=>learnerDetail(b.dataset.learner));});
 document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{classId=b.dataset.class;tab='learners';render()});
 document.querySelectorAll('[data-add-learner]').forEach(b=>b.onclick=()=>{data.learners.push({id:crypto.randomUUID(),classId:b.dataset.addLearner,name:`Demo learner ${data.learners.length+1}`});save();render();notice('Demo learner added. No invitation was sent.');});
 document.querySelectorAll('[data-assignment]').forEach(b=>b.onclick=()=>assignmentDetail(b.dataset.assignment));
 document.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>{const t=data.support.find(t=>t.id===b.dataset.ticket);download(`support-draft-${t.id.slice(0,8)}.txt`,`NOT SUBMITTED — LOCAL DEMO DRAFT\nSubject: ${t.subject}\nCategory: ${t.category}\nDate: ${t.date}\n\n${t.body}`,'text/plain');});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]());
}
let lastFocus;
function modal(title,body,onSubmit){lastFocus=document.activeElement;const d=$('#editor');d.innerHTML=`<button class="editor-close" aria-label="Close dialog">×</button><h2 id="editor-title">${escape(title)}</h2>${body}`;d.querySelector('.editor-close').onclick=()=>d.close();d.onclose=()=>lastFocus?.isConnected&&lastFocus.focus();d.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();try{onSubmit(new FormData(e.target));save();d.close();render();notice(storageOK?'Saved in this demo workspace.':'Saved for this visit only.');}catch(err){d.querySelector('.form-error').textContent=err.message;}});d.showModal();}
function learnerDetail(id){const l=data.learners.find(l=>l.id===id),attempts=scopedAttempts(data,'all',days).filter(a=>a.learnerId===id),m=metrics(attempts);modal(l.name,`<p class="section-note">${escape(className(l.classId))} · ${days?`Last ${days} days`:'All time'} · Sample learner</p><div class="detail-stats"><div><strong>${m.sessions}</strong><span>Completed lessons</span></div><div><strong>${pct(m.accuracy)}</strong><span>First-try accuracy</span></div></div><h3>Recent completed practice</h3>${attempts.length?`<ul class="practice-history">${[...attempts].sort((a,b)=>b.date.localeCompare(a.date)).map(a=>`<li><span>${escape(lessonMap.get(a.lessonId)?.title||'Figure '+a.lessonId)}<small>${dateLabel(a.date)} · ${a.minutes} min${Number.isInteger(a.supportSteps)?' · '+a.supportSteps+' steps with app support':' · Support not recorded'}</small></span><b>${a.firstTry}/${a.questions}<small>first try</small></b></li>`).join('')}</ul>`:empty('No practice in this period','Try a longer reporting period or check in with the learner.')}`);}
function assignmentDetail(id){const a=data.assignments.find(a=>a.id===id),progress=assignmentProgress(data,a);modal(a.title,`<p class="section-note">${escape(className(a.classId))} · Due ${dateLabel(a.due)} · Demo only, not delivered</p><h3>Assigned figures</h3><ul>${a.lessonIds.map(id=>`<li>${escape(lessonMap.get(id)?.title||'Figure '+id)}</li>`).join('')}</ul>${a.instructions?`<p class="section-note">${escape(a.instructions)}</p>`:''}${a.mode==='homework'?`<div class="homework-settings"><strong>Try the learner experience</strong><p>Choose a fictional learner. Completing homework here updates this browser’s demo reports.</p><label>Demo learner<select id="homework-learner">${a.learnerIds.map(id=>`<option value="${id}">${escape(data.learners.find(l=>l.id===id)?.name||'Demo learner')}</option>`).join('')}</select></label><button class="org-button org-primary" id="try-homework">Open homework preview →</button></div>`:''}<h3>Assignment completion</h3><p class="section-note">Support includes hints, examples, or corrective guidance shown before an answer. No app support recorded does not establish independent work. In-class verification is not connected yet.</p><ul class="practice-history">${progress.map(r=>`<li><span>${escape(data.learners.find(l=>l.id===r.id)?.name||'Learner')}</span><b class="org-status ${r.done?'status-good':''}">${escape(r.status)}</b></li>`).join('')}</ul>`);$('#try-homework')?.addEventListener('click',()=>{location.href='../index.html?homeworkDemo='+encodeURIComponent(a.id)+'&learner='+encodeURIComponent($('#homework-learner').value);});}
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type:type+';charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Download prepared.');}
const formEnd=label=>`<p class="form-error" role="alert"></p><button class="org-button org-primary" type="submit">${label}</button></form>`;
const actions={
 class:()=>modal('Create a demo class',`<p class="section-note">Use a fictional group name while exploring.</p><form><label>Class name<input name="name" maxlength="60" required placeholder="e.g. Thursday algebra club"></label><label>Description<textarea name="description" maxlength="140" placeholder="Schedule or practice focus"></textarea></label>${formEnd('Create class')}`,f=>addClass(data,{name:f.get('name'),description:f.get('description')})),
 assignment:(selected=[])=>modal('Create homework practice',`<p class="section-note">Saved in this workspace. Student delivery is not connected yet. Homework keeps hints, examples, sounds, and celebrations enabled.</p><form><div class="homework-settings"><strong>Homework practice</strong><p>Self-paced · Support encouraged · No timer</p><small>In-class checks will be added separately.</small></div><label>Teacher instructions (optional)<textarea name="instructions" maxlength="500" placeholder="What should your class focus on?"></textarea></label><label>Title<input name="title" required maxlength="80" value="${escape(selected.length===1?lessonMap.get(selected[0])?.title: selected.length?'Unit practice':'')}" placeholder="e.g. This week’s equation practice"></label><label>Class<select name="classId">${data.classes.map(c=>`<option value="${c.id}" ${classId===c.id?'selected':''}>${escape(c.name)}</option>`).join('')}</select></label><label>Due date<input type="date" name="due" required min="${dayKey()}" value="${daysAgo(-7)}"></label><fieldset><legend>Choose figures</legend><div class="lesson-picks">${available.map(l=>`<label><input type="checkbox" name="lessons" value="${l.id}" ${selected.includes(l.id)?'checked':''}><span>Figure ${l.id} · ${escape(l.title)}</span></label>`).join('')}</div></fieldset>${formEnd('Save demo assignment')}`,f=>addAssignment(data,{title:f.get('title'),classId:f.get('classId'),due:f.get('due'),instructions:f.get('instructions'),lessonIds:f.getAll('lessons').map(Number)},available.map(l=>l.id))),
 support:()=>modal('Draft a support request',`<p class="section-note">This saves a draft; it does not send a message. Do not include student names, emails, or other personal information.</p><form><label>Topic<select name="category"><option>Getting started</option><option>Lessons and answers</option><option>Reporting</option><option>Technical issue</option></select></label><label>Subject<input name="subject" maxlength="100" required></label><label>What happened?<textarea name="body" rows="5" maxlength="3000" required placeholder="What were you trying to do? What did you expect? What happened instead?"></textarea></label>${formEnd('Save draft')}`,f=>{const subject=f.get('subject').trim(),body=f.get('body').trim();if(!subject||!body)throw Error('Add a subject and description.');data.support.push({id:crypto.randomUUID(),subject,body,category:f.get('category'),date:dayKey()});}),
 export:()=>{const attempts=scopedAttempts(data,classId,days);const rows=[['DEMO DATA — not real student results'],['Period',days?`Last ${days} days`:'All time'],['Class','Learner','Completed sessions','Scored questions','First-try accuracy (%)','Practice minutes','Practice signal']];for(const l of scopedLearners(data,classId)){const a=attempts.filter(a=>a.learnerId===l.id),m=metrics(a);rows.push([className(l.classId),l.name,m.sessions,m.questions,m.accuracy??'',m.minutes,learnerStatus(a)]);}download(`reckoning-demo-report-${dayKey()}.csv`,csv(rows),'text/csv');},
 reset:()=>modal('Reset this demo?',`<p class="section-note">This removes classes, assignments, and support drafts you created in this demo. Learner-app progress is separate and will not be affected.</p><form>${formEnd('Reset demo')}`,()=>{data=seed();classId='all';search='';})
};
// Teacher planning notes describe the existing course; they are not verified standards alignment.
const unitNotes={
 1:['Solve linear equations using inverse operations, including multi-step equations and word problems.','Signed-number arithmetic, fractions, decimals, and order of operations.'],
 2:['Solve linear inequalities, handle sign reversal, and interpret solution sets on a number line.','Linear equations and comparing signed numbers.'],
 3:['Explore unit conversions and the available systems applications. Several lessons in this unit are not yet available.','Linear equations, coordinate graphs, and proportional reasoning.'],
 4:['Explore quadratic equations through factoring, completing the square, the quadratic formula, and graphs.','Linear equations, polynomial multiplication, factoring, and square roots.'],
 5:['Classify, combine, multiply, and divide polynomials; connect expressions to area.','Distributive property, like terms, and basic exponent notation.'],
 6:['Apply exponent rules, scientific notation, and radical operations.','Multiplication, division, fractions, and powers.'],
 7:['Interpret and work with functions, including representations, operations, composition, and inverses.','Equations, coordinate graphs, substitution, and inequalities.']
};
let curriculumSearch='',unitFilter='all';
function plain(value){const t=document.createElement('template');t.innerHTML=String(value??'');return t.content.textContent||'';}
// Only course formatting is retained; no inline event handlers, styles, or embedded content.
function courseMarkup(value){const t=document.createElement('template');t.innerHTML=String(value??'');for(const denominator of [...t.content.querySelectorAll('span[style]')]){if(denominator.style.borderTop&&denominator.previousElementSibling){const numerator=denominator.previousElementSibling;denominator.parentElement.replaceWith(document.createTextNode('('+numerator.textContent+')/('+denominator.textContent+')'));}}for(const el of [...t.content.querySelectorAll('*')].reverse()){if(!['DIV','SPAN','P','BR','B','STRONG','EM','I','SUP','SUB','UL','OL','LI'].includes(el.tagName)){el.replaceWith(document.createTextNode(el.textContent));}else for(const attr of [...el.attributes])el.removeAttribute(attr.name);}return t.innerHTML;}
function curriculumView(){return `<section class="org-panel curriculum-intro"><span class="org-kicker">ALGEBRA 1 · EXISTING COURSE</span><h2>A clear view of the learning path</h2><p>Browse ${course.length} units and ${course.flatMap(m=>m.lessons).filter(l=>l.available).length} available figures. Preview the original lesson steps, then choose practice for your class.</p><p class="panel-note">Planning objectives and prerequisites are suggested teaching notes. Standards alignment has not been verified. Course order is shown as it exists today; prerequisites may call for material from a later unit.</p></section><div class="curriculum-controls"><label>Search curriculum<input id="curriculum-search" type="search" value="${escape(curriculumSearch)}" placeholder="Try fractions, graphing, or factoring"></label><label>Unit<select id="unit-filter"><option value="all">All units</option>${course.map(m=>`<option value="${m.id}" ${unitFilter===String(m.id)?'selected':''}>${escape(m.name)}</option>`).join('')}</select></label></div><div id="curriculum-results">${curriculumUnits()}</div>`;}
function curriculumUnits(){const query=curriculumSearch.trim().toLowerCase();const units=course.filter(m=>unitFilter==='all'||String(m.id)===unitFilter).map(m=>({...m,lessons:m.lessons.filter(l=>`${m.name} ${l.id} ${l.title} ${(l.questions||[]).map(q=>plain(q.q)).join(' ')}`.toLowerCase().includes(query))})).filter(m=>m.lessons.length);return units.length?units.map(m=>`<section class="org-panel curriculum-unit"><header><span class="unit-number">${String(m.id).padStart(2,'0')}</span><div><span class="org-kicker">UNIT ${m.id}</span><h2>${escape(m.name)}</h2></div></header><div class="unit-notes"><div><strong>Learning objective</strong><p>${escape(unitNotes[m.id][0])}</p></div><div><strong>Suggested prerequisites</strong><p>${escape(unitNotes[m.id][1])}</p></div></div><div class="curriculum-lessons">${m.lessons.map(l=>`<article class="curriculum-lesson"><div><small>FIGURE ${String(l.id).padStart(3,'0')}</small><h3>${escape(l.title)}</h3><span class="org-status ${l.available&&!l.premium?'status-good':''}">${!l.available?'Not available':l.premium?'Premium · Preview only':'Assignable in demo'}</span>${l.available?`<span class="step-count">${l.questions.length} original steps</span>`:''}</div><div class="curriculum-actions">${l.available?`<button class="org-button" data-preview-lesson="${l.id}">Preview lesson</button>`:''}${l.available&&!l.premium?`<button class="org-text-button" data-assign-lesson="${l.id}">Assign figure →</button>`:''}</div></article>`).join('')}</div></section>`).join(''):empty('No matching figures','Try a different topic or choose all units.');}
function bindCurriculumRows(){document.querySelectorAll('[data-preview-lesson]').forEach(b=>b.onclick=()=>previewLesson(Number(b.dataset.previewLesson)));document.querySelectorAll('[data-assign-lesson]').forEach(b=>b.onclick=()=>actions.assignment([Number(b.dataset.assignLesson)]));}
function bindCurriculum(){bindCurriculumRows();$('#curriculum-search')?.addEventListener('input',e=>{curriculumSearch=e.target.value;$('#curriculum-results').innerHTML=curriculumUnits();bindCurriculumRows();});$('#unit-filter')?.addEventListener('change',e=>{unitFilter=e.target.value;$('#curriculum-results').innerHTML=curriculumUnits();bindCurriculumRows();});}
function previewLesson(id){const l=lessonMap.get(id);if(!l?.available)return;const unit=course.find(m=>m.lessons.some(item=>item.id===id));modal(l.title,`<p class="section-note">Unit ${unit.id} · Figure ${id} · Teacher content preview<br>Original questions and answer key. Learner animations and optional coaching are not shown.${id===2?' The learner experience also includes an extra two-step challenge.':''}</p>${l.premium?'<p class="org-status">Premium · Assignment access is not enabled in this demo</p>':`<button class="org-button org-primary" id="assign-preview">Assign this figure</button>`}<ol class="question-preview">${l.questions.map(q=>`<li><span class="org-kicker">${escape(q.type.replaceAll('-',' '))}</span>${q.concept?`<details><summary>Teaching explanation</summary><div class="course-copy">${courseMarkup(q.concept)}</div></details>`:''}${q.eq?`<div class="preview-equation">${courseMarkup(q.eq)}</div>`:''}<p>${courseMarkup(q.q||q.text||'')}</p>${q.content?`<div class="course-copy">${courseMarkup(q.content)}</div>`:''}${q.visual?`<p class="panel-note">Number-line illustration: ${escape(q.visual.type==='basic-line'?'Number line from −5 to 5':q.visual.type==='comparison'?q.visual.left.label+' compared with '+q.visual.right.label:q.visual.inequality+'; '+q.visual.type.replaceAll('-',' ')+' at '+q.visual.position+', shaded '+q.visual.shade)}</p>`:''}${q.choices?`<ul>${q.choices.map(c=>`<li>${courseMarkup(c)}</li>`).join('')}</ul>`:''}${q.answer!==undefined?`<details class="answer-key"><summary>Show answer</summary><p>${courseMarkup(q.type==='multiple-choice'?q.choices[q.answer]:q.type==='graph'?`${q.answer.circleType} circle at ${q.answer.position}, shade ${q.answer.direction}`:q.type==='true-false'?(q.answer?'True':'False'):q.answer)}</p></details>`:'<p class="panel-note">Teaching step · No answer required</p>'}</li>`).join('')}</ol>`);$('#assign-preview')?.addEventListener('click',()=>{$('#editor').close();actions.assignment([id]);});}

render();
