import {schoolCourseAccess} from './course-access.js?v=b1f8d392848e';
import * as api from '../owner/client.js?v=0842e0954dba';
import {course} from '../course.js?v=4cb03d5dcbbc';
const app=document.querySelector('#classroom-app'),p=new URLSearchParams(location.search),s=p.get('school'),c=p.get('class');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=id=>/^[A-Za-z0-9_-]{1,128}$/.test(id||'');
const root=()=>`classroom.html?school=${encodeURIComponent(s)}`;
const brand='<a class="org-brand" href="../"><img src="../assets/brand-transparent.png" alt=""><span>Reckoning Figures<small>EDUCATOR WORKSPACE</small></span></a>';
const plus='<svg class="staff-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>';
let ctx,user,epoch=0,tab='assignments',klass,assignments=[],roster=[],invite=null,requests=[];
const manager=()=>ctx.owner||['administrator','teacher'].includes(ctx.member?.role);
const err=e=>e.code==='permission-denied'?'This action is unavailable. Check the school’s seats, license, permissions, and that the newest rules are activated.':e.code?.startsWith('auth/')?'Unable to sign in. Check your account and try again.':e.message||'Could not connect. Try again.';
function frame(body){app.innerHTML=`<header class="owner-header">${brand}<div class="staff-actions"><a class="org-button" href="./?school=${encodeURIComponent(s)}">School</a>${ctx&&(ctx.owner||['teacher','administrator'].includes(ctx.member?.role))?`<a class="org-button" href="../support.html?school=${encodeURIComponent(s)}">Support</a>`:''}<button id="logout" class="org-button">Sign out</button></div></header>${body}`;document.querySelector('#logout').onclick=()=>api.logout();}
function toast(text){document.querySelector('.staff-toast')?.remove();const el=document.createElement('div');el.className='staff-toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),4000);}
function modal(title,body){document.querySelector('#staff-dialog')?.remove();const d=document.createElement('dialog');d.id='staff-dialog';d.setAttribute('aria-labelledby','dialog-title');d.innerHTML=`<button class="staff-close" aria-label="Close">×</button><h2 id="dialog-title">${title}</h2>${body}`;const trigger=document.activeElement;document.body.append(d);d.querySelector('.staff-close').onclick=()=>d.close();d.onclose=()=>{d.remove();if(trigger?.isConnected)trigger.focus();};d.showModal();return d;}
function help(){return `<details class="staff-help"><summary>A quick guide to this workspace</summary>${manager()?'<ol><li>Create a class, then use Invite students to make a join link.</li><li>Students register or sign in from that link. Choose automatic entry or approve requests.</li><li>With an active Algebra 1 school license, select Assign practice, choose any of the seven units and its figures, then save. Students do not need an individual Premium purchase.</li><li>Review results from the assignment card. Use Refresh to see new completions.</li></ol><p><a href="../curriculum.html">View curriculum coverage and review status</a></p>':'<ol><li>Open an assignment below and choose a figure.</li><li>Use hints whenever you need them.</li><li>Finish the figure and wait for the save before closing the page.</li></ol>'}<p>Only first saved completions are reported. App support is recorded; outside help is unknown. Use test accounts until privacy and live pilot checks are complete.</p></details>`;}
function login(){app.innerHTML=`<div class="join-shell">${brand}<section class="org-panel"><span class="staff-badge">WELCOME BACK</span><h1 class="join-title">Your classroom,<br>at a glance.</h1><form class="staff-form"><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><p class="staff-error" id="login-error" role="alert"></p><button class="org-button org-primary">Sign in</button></form><button id="google" class="org-button" style="width:100%;margin-top:12px">Continue with Google</button></section></div>`;const run=async fn=>{try{await fn();}catch(e){const el=document.querySelector('#login-error');if(el)el.textContent=err(e);}};app.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);run(()=>api.login(f.get('email').trim(),f.get('password')));};document.querySelector('#google').onclick=()=>run(api.googleLogin);}
function action(form,fn){form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('[type=submit]'),msg=form.querySelector('[role=alert]');b.disabled=true;msg.textContent='Saving…';try{await fn(new FormData(form));}catch(e){msg.textContent=err(e);}finally{b.disabled=false;}};}
async function createClass(){let teachers=[];try{if(ctx.member?.role!=='teacher')teachers=(await api.members(s)).filter(m=>m.role==='teacher'&&m.state==='active');}catch(e){toast(err(e));return;}
 const d=modal('Create a class',`<p class="panel-note">A dedicated place for practice, progress, and your students.</p><form class="staff-form" id="create-class"><label>Class name<input name="name" maxlength="80" required placeholder="e.g. Algebra · Period 2" autofocus></label>${ctx.member?.role==='teacher'?'':`<label>Teacher<select name="teacher" required><option value="">Choose an active teacher</option>${teachers.map(t=>`<option value="${esc(t.uid)}">${esc(t.label)}</option>`).join('')}</select></label>${teachers.length?'':'<p class="panel-note">Add a teacher under School → Members first.</p>'}`}<p class="staff-error" role="alert"></p><button type="submit" class="org-button org-primary">Create class</button></form>`);action(d.querySelector('form'),async f=>{const id=await api.classroom.createClass(s,f.get('name'),ctx.member?.role==='teacher'?user.uid:f.get('teacher'));location.href=root()+'&class='+encodeURIComponent(id);});}
async function load(){const token=++epoch;try{ctx=await api.schoolContext(s);if(token!==epoch)return;
 if(!c){const classes=manager()?await api.classroom.classes(s,ctx.owner||ctx.member?.role==='administrator'):[];if(token!==epoch)return;
 frame(`<header class="org-heading"><div><span class="org-kicker">${esc(ctx.school.name)}</span><h1>Your classes.</h1><p class="staff-subtle">Your classes, ready when you are.</p></div>${manager()?`<button id="new-class" class="org-button org-primary">${plus} New class</button>`:''}</header>${manager()?`<div class="staff-grid">${classes.map(x=>`<a class="staff-card staff-card-link" href="${root()}&class=${encodeURIComponent(x.id)}"><span class="staff-badge">ALGEBRA 1</span><h2>${esc(x.name)}</h2><p class="staff-subtle">Assignments · Students · Results</p><span class="staff-actions">Open class →</span></a>`).join('')}</div>${classes.length?'':'<section class="staff-empty"><h2>Start with your first class.</h2><p>Create it once. Invite students with a link. Keep the work together.</p><button id="empty-create" class="org-button org-primary">Create a class</button></section>'}`:'<section class="staff-empty"><h2>Your teacher has your invitation.</h2><p>Open your class join link to register or connect this account. No student ID needed.</p></section>'}${help()}`);document.querySelector('#new-class')?.addEventListener('click',createClass);document.querySelector('#empty-create')?.addEventListener('click',createClass);return;}
 const info=await api.classroom.classInfo(s,c),work=await api.classroom.assignments(s,c),people=manager()?await api.classroom.classRoster(s,c):[],link=manager()?await api.invitations.current(s,c):null,waiting=link?.active&&manager()?await api.invitations.pending(link.token):[];
 if(token!==epoch)return;klass=info;assignments=work;roster=people;invite=link;requests=waiting;render();
 }catch(e){if(token!==epoch)return;frame(`<section class="org-panel"><h1 class="join-title">Let’s check your access.</h1><p>${esc(err(e))}</p><button class="org-button" id="retry">Try again</button></section>`);document.querySelector('#retry').onclick=load;}}
function render(){frame(`<header class="org-heading"><div><a class="staff-badge" href="${root()}">${esc(ctx.school.name)} / Classes</a><h1>${esc(klass.name)}</h1></div><div class="staff-actions">${manager()?'<button id="invite" class="org-button">Invite students</button><button id="assign" class="org-button org-primary" '+(schoolCourseAccess(ctx.school).open?'':'disabled')+'>'+plus+' Assign practice</button>':''}</div></header><div class="staff-summary">${manager()?`<span><strong>${roster.length}</strong> students</span>`:''}<span><strong>${assignments.length}</strong> assignments</span><span>${esc(schoolCourseAccess(ctx.school).message)}</span><button id="refresh" class="org-text-button">Refresh</button></div>${manager()?`<nav class="staff-tabs" aria-label="Class sections" role="tablist">${[['assignments','Assignments',assignments.length],['students','Students',roster.length],['requests','Requests',requests.length]].map(([id,label,n])=>`<button role="tab" aria-selected="${tab===id}" data-tab="${id}">${label}<span>${n}</span></button>`).join('')}</nav>`:''}<section id="class-content"></section>${help()}`);
 document.querySelector('#refresh').onclick=load;document.querySelector('#invite')?.addEventListener('click',inviteDialog);document.querySelector('#assign')?.addEventListener('click',assignDialog);app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();document.querySelector(`[data-tab="${tab}"]`)?.focus();});
 if(!manager()||tab==='assignments')renderAssignments();else if(tab==='students')renderStudents();else renderRequests();}
function renderAssignments(){const el=document.querySelector('#class-content');el.innerHTML=assignments.length?`<div class="staff-grid">${assignments.map(a=>`<article class="staff-card"><span class="staff-badge">HOMEWORK · ${a.lessonIds.length} ${a.lessonIds.length===1?'FIGURE':'FIGURES'}</span><h2>${esc(a.title)}</h2><small>Due ${esc(a.due)}</small>${a.instructions?`<p class="staff-subtle">${esc(a.instructions)}</p>`:''}<div class="staff-actions">${manager()?`<button class="org-button" data-report="${esc(a.id)}">Review results</button>`:`<a class="org-button org-primary" href="../?schoolHomework=${encodeURIComponent(a.id)}&school=${encodeURIComponent(s)}&class=${encodeURIComponent(c)}">Start practice →</a>`}</div></article>`).join('')}</div>`:`<section class="staff-empty"><h2>${manager()?'Make room for a small win.':'You’re in. Your next step is coming.'}</h2><p>${manager()?'Assign a few figures or an entire unit. Students will see them here.':'Your teacher’s assignments will appear here. Check back soon.'}</p>${manager()?'<button id="empty-assign" class="org-button org-primary" '+(schoolCourseAccess(ctx.school).open?'':'disabled')+'>Assign practice</button>':''}</section>`;document.querySelector('#empty-assign')?.addEventListener('click',assignDialog);el.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>report(b.dataset.report));}
function renderStudents(){const el=document.querySelector('#class-content');el.innerHTML=roster.length?`<div class="staff-table-wrap"><table class="staff-table"><thead><tr><th>Student</th><th>Class access</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>${roster.map(r=>`<tr><td>${esc(r.label)}</td><td>Enrolled</td><td><button class="org-button" data-remove="${esc(r.id)}">Remove</button></td></tr>`).join('')}</tbody></table></div><p class="panel-note">Removing class access keeps saved results. School seat allocation is managed under School.</p>`:'<section class="staff-empty"><h2>Invite your first student.</h2><p>Share one link. Students create an account or sign in and join this class.</p><button id="empty-invite" class="org-button org-primary">Invite students</button></section>';document.querySelector('#empty-invite')?.addEventListener('click',inviteDialog);el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api.classroom.unenroll(s,c,b.dataset.remove);await load();toast('Class access removed. Saved results retained.');}catch(e){toast(err(e));b.disabled=false;}});}
function renderRequests(){const el=document.querySelector('#class-content');el.innerHTML=requests.length?`<div class="staff-table-wrap"><table class="staff-table"><thead><tr><th>Student</th><th>Requested access</th><th>Decision</th></tr></thead><tbody>${requests.map(r=>`<tr><td>${esc(r.label)}</td><td>Student</td><td><div class="staff-actions"><button class="org-button org-primary" data-approve="${esc(r.uid)}">Approve</button><button class="org-button" data-reject="${esc(r.uid)}">Decline</button></div></td></tr>`).join('')}</tbody></table></div>`:`<section class="staff-empty"><h2>All caught up.</h2><p>${invite?.mode==='automatic'?'Your current link admits students automatically. Change admission settings under Invite students if you prefer to approve requests.':'New join requests will appear here when students use your approval link.'}</p></section>`;for(const kind of ['approve','reject'])el.querySelectorAll('[data-'+kind+']').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api.invitations[kind](invite.token,b.dataset[kind]);await load();toast(kind==='approve'?'Student admitted.':'Request declined.');}catch(e){toast(err(e));b.disabled=false;}});}
function inviteURL(i){return new URL('join.html?invite='+encodeURIComponent(i.token),location.href).href;}
function inviteDialog(){const active=invite?.active&&(!invite.expiresAt||invite.expiresAt.toMillis()>Date.now());const d=modal('Invite students',`<p class="panel-note">Students register or sign in, then join this class. Their ID and school seat are handled automatically.</p>${active?`<label class="staff-form">Your join link<input class="invite-link" readonly value="${esc(inviteURL(invite))}"></label><div class="staff-actions" style="margin:16px 0"><button id="copy-link" class="org-button org-primary">Copy link</button><button id="revoke-link" class="org-button">Turn off</button></div><p class="panel-note">${invite.mode==='automatic'?'Automatic admission':'Teacher approval required'} · ${invite.expiresAt?'Expires '+invite.expiresAt.toDate().toLocaleDateString():'No expiry'}</p>`:''}<${active?'details':'div'}><${active?'summary':'h3'}>${active?'Replace link & admission settings':'Choose how students join'}</${active?'summary':'h3'}><form class="staff-form" id="invite-form" style="margin-top:18px"><label>Admission<select name="mode"><option value="automatic" ${invite?.mode==='automatic'?'selected':''}>Automatic · fewest steps</option><option value="approval" ${invite?.mode==='approval'?'selected':''}>Approve each request</option></select></label><label>Link expires<select name="days"><option value="30">In 30 days</option><option value="7">In 7 days</option><option value="0">No expiry</option></select></label>${active?'<p class="panel-note">Replacing turns off the old link. Pending students must use the new link; existing students keep class access.</p>':''}<p class="staff-error" role="alert"></p><button type="submit" class="org-button org-primary">${active?'Replace':'Create'} & copy link</button></form></${active?'details':'div'}><p id="invite-feedback" role="status" class="panel-note"></p>`);
 const copy=async()=>{try{await navigator.clipboard.writeText(inviteURL(invite));document.querySelector('#invite-feedback').textContent='Copied. Share this link with your students.';}catch{const input=d.querySelector('.invite-link');input?.focus();input?.select();document.querySelector('#invite-feedback').textContent='Select and copy the link above.';}};
 document.querySelector('#copy-link')?.addEventListener('click',copy);document.querySelector('#revoke-link')?.addEventListener('click',async e=>{e.target.disabled=true;try{await api.invitations.revoke(invite.token);d.close();await load();toast('Invitation turned off. Existing students keep access.');}catch(error){document.querySelector('#invite-feedback').textContent=err(error);e.target.disabled=false;}});
 action(d.querySelector('form'),async f=>{invite=await api.invitations.create(s,c,{schoolName:ctx.school.name,className:klass.name,mode:f.get('mode'),days:Number(f.get('days')),previous:invite?.token||null});d.close();inviteDialog();try{await navigator.clipboard.writeText(inviteURL(invite));document.querySelector('#invite-feedback').textContent='Copied. Share this link with your students.';}catch{document.querySelector('#invite-feedback').textContent='Your link is ready. Use Copy link or select it above.';}requests=[];});}
function assignDialog(){const access=schoolCourseAccess(ctx.school);if(!access.open){toast(access.message);return;}const due=new Date();due.setDate(due.getDate()+7);const dueValue=due.getFullYear()+'-'+String(due.getMonth()+1).padStart(2,'0')+'-'+String(due.getDate()).padStart(2,'0');const d=modal('Assign practice',`<form class="staff-form" id="assignment"><div class="staff-split"><label>Title<input name="title" maxlength="80" required value="Algebra practice"></label><label>Due date<input name="due" type="date" required value="${dueValue}"></label></div><label>Unit<select id="unit">${course.map((u,i)=>`<option value="${i}">${esc(u.name)}</option>`).join('')}</select></label><div class="staff-actions"><button type="button" id="select-unit" class="org-button">Select unit</button><button type="button" id="clear-unit" class="org-button">Clear unit</button><span id="selected-count" class="panel-note" role="status"></span></div><fieldset id="figures"></fieldset><details><summary>Teacher instructions (optional)</summary><label style="margin-top:12px">Instructions<textarea name="instructions" maxlength="500" rows="3"></textarea></label></details><p class="panel-note">Selections stay when you switch units. Available figures only. Students added later can also access this assignment.</p><p class="staff-error" role="alert"></p><button type="submit" class="org-button org-primary">Assign to class</button></form>`);
 const selected=new Set(),unit=d.querySelector('#unit'),available=()=>course[Number(unit.value)].lessons.filter(l=>l.available&&l.questions?.length);const count=()=>d.querySelector('#selected-count').textContent=selected.size+' selected';const draw=()=>{d.querySelector('#figures').innerHTML=`<legend>Figures</legend>${available().map(l=>`<label class="lesson-choice"><input type="checkbox" value="${l.id}" ${selected.has(l.id)?'checked':''}>${esc(l.title)} <span class="staff-subtle">· ${l.id}</span></label>`).join('')||'<p>No available figures in this unit.</p>'}`;count();d.querySelectorAll('#figures input').forEach(i=>i.onchange=()=>{i.checked?selected.add(Number(i.value)):selected.delete(Number(i.value));count();});};unit.onchange=draw;d.querySelector('#select-unit').onclick=()=>{available().forEach(l=>selected.add(l.id));draw();};d.querySelector('#clear-unit').onclick=()=>{available().forEach(l=>selected.delete(l.id));draw();};draw();
 action(d.querySelector('form'),async f=>{if(!selected.size)throw Error('Choose at least one figure.');await api.classroom.createAssignment(s,c,{title:f.get('title').trim(),instructions:f.get('instructions').trim(),due:f.get('due'),lessonIds:[...selected].sort((a,b)=>a-b)});d.close();tab='assignments';await load();toast('Assigned. Students can start from their class page.');});}
async function report(id){const a=assignments.find(a=>a.id===id),d=modal(esc(a.title),'<p role="status">Loading first-completion results…</p>');try{const rows=await api.classroom.results(s,c,id,true);if(!d.isConnected)return;const people=[...roster,...[...new Set(rows.map(r=>r.uid))].filter(uid=>!roster.some(p=>p.id===uid)).map(id=>({id,label:'Former class member'}))];d.querySelector('[role=status]').outerHTML=`<p class="panel-note">First saved completion per figure. App support is shown separately from independent understanding.${rows.length>=1000?' Result limit reached: this report may be incomplete.':''}</p><div class="staff-table-wrap"><table class="staff-table"><thead><tr><th>Student</th><th>Figures</th><th>First try</th><th>App support</th></tr></thead><tbody>${people.map(p=>{const r=rows.filter(x=>x.uid===p.id),q=r.reduce((n,x)=>n+x.questions,0),first=r.reduce((n,x)=>n+x.firstTry,0),support=r.reduce((n,x)=>n+x.supportSteps,0);return `<tr><td>${esc(p.label)}</td><td>${r.length}/${a.lessonIds.length}</td><td>${q?Math.round(first/q*100)+'%':'—'}</td><td>${r.length?support+' steps':'—'}</td></tr>`;}).join('')}</tbody></table></div>${people.length?'':'<p>No students or results yet.</p>'}<p class="panel-note">Client-reported homework practice. Outside help is unknown. A completion is not an independent assessment.</p>`;}catch(e){d.querySelector('[role=status]').textContent=err(e);}}
api.observe(u=>{epoch++;document.querySelector('#staff-dialog')?.close();user=u;if(!valid(s)||(c&&!valid(c))){app.innerHTML='<p>Open the school or class link supplied by your administrator.</p>';return;}if(!u)login();else load();});
