import * as api from '../owner/client.js?v=e4a08315fb05';
import {course} from '../course.js';
const app=document.querySelector('#classroom-app'),p=new URLSearchParams(location.search),s=p.get('school'),c=p.get('class');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=id=>/^[A-Za-z0-9_-]{1,128}$/.test(id||'');
const root=()=>`classroom.html?school=${encodeURIComponent(s)}`;
const brand='<a class="org-brand" href="../"><img src="../assets/brand-transparent.png" alt=""><span>Reckoning Figures<small>CONNECTED CLASSES</small></span></a>';
let ctx,user,epoch=0;
const err=e=>e.code==='permission-denied'?'Access denied. Check your school/class membership, license dates, and that the connected-class rules have been published.':e.code?.startsWith('auth/')?'Unable to sign in. Check your account and try again.':e.message||'Could not connect. Try again.';
function frame(body){app.innerHTML=`<header class="owner-header">${brand}<div class="class-actions"><a class="org-button" href="./?school=${encodeURIComponent(s)}">School access</a><button id="logout" class="org-button">Sign out</button></div></header>${body}`;document.querySelector('#logout').onclick=()=>api.logout();}
function help(manager){return `<details class="org-panel"><summary>How to use your ${manager?'class workspace':'assigned practice'}</summary>${manager?'<ol><li>Create a class using an active teacher account.</li><li>Add existing school students by UID. Enrollment does not create an account or use an additional seat.</li><li>Select a unit, choose its figures, and save the assignment.</li><li>Share the class link with those students.</li><li>Open Review results after students finish. Refresh to load new completions.</li></ol>':'<ol><li>Use the account your school enrolled in this class.</li><li>Open an assignment and choose a figure.</li><li>Use hints whenever you need them.</li><li>Finish the figure and keep the page open until the result saves. If saving fails, reconnect and retry.</li></ol>'}<p class="panel-note">For this pilot, use fictional test accounts. Only the first saved completion per figure is reported. Homework does not demonstrate independent mastery. Class and assignment editing is not available yet.</p></details>`;}
function login(){app.innerHTML=`${brand}<section class="org-panel owner-login"><h1>Sign in to your class</h1><form class="class-form"><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button class="org-button org-primary">Sign in</button></form><button id="google" class="org-button">Continue with Google</button><p id="login-error" role="alert"></p></section>`;const run=async fn=>{try{await fn();}catch(e){const el=document.querySelector('#login-error');if(el)el.textContent=err(e);}};app.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);run(()=>api.login(f.get('email').trim(),f.get('password')));};document.querySelector('#google').onclick=()=>run(api.googleLogin);}
function formAction(form,fn){form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;const status=form.querySelector('[role=alert]');status.textContent='Saving…';try{await fn(new FormData(form));}catch(e){status.textContent=err(e);}finally{button.disabled=false;}};}
async function load(){const token=++epoch;try{
 ctx=await api.schoolContext(s);if(token!==epoch)return;
 const manager=ctx.owner||ctx.member?.role==='administrator'||ctx.member?.role==='teacher';
 if(!c){const classes=manager?await api.classroom.classes(s,ctx.owner||ctx.member?.role==='administrator'):[];if(token!==epoch)return;
 frame(`<header class="org-heading"><div><span class="org-kicker">${esc(ctx.school.name)}</span><h1>Your classes</h1></div></header>${help(manager)}${manager?`<section class="org-panel"><h2>Create a class</h2><form id="create-class" class="class-form"><label>Class name<input name="name" maxlength="80" required placeholder="Algebra foundations"></label>${ctx.member?.role==='teacher'?'':`<label>Teacher account UID<input name="teacher" pattern="[A-Za-z0-9_-]{1,128}" required placeholder="Existing active teacher in this school"></label>`}<p role="alert"></p><button type="submit" class="org-button org-primary">Create class</button></form></section><section class="org-panel"><h2>Classes</h2><p class="panel-note">Showing up to 100 classes.</p>${classes.length?classes.map(x=>`<p><a class="org-button" href="${root()}&class=${encodeURIComponent(x.id)}">${esc(x.name)}</a></p>`).join(''):'<p>No classes yet.</p>'}</section>`:'<section class="org-panel"><h2>Ask your teacher for your class link</h2><p>Use the same link on your phone or computer. Your account must be enrolled first.</p></section>'}`);
 if(manager)formAction(document.querySelector('#create-class'),async f=>{const id=await api.classroom.createClass(s,f.get('name'),ctx.member?.role==='teacher'?user.uid:f.get('teacher').trim());location.href=root()+'&class='+encodeURIComponent(id);});return;
 }
 const klass=await api.classroom.classInfo(s,c),assignments=await api.classroom.assignments(s,c),roster=manager?await api.classroom.classRoster(s,c):[];if(token!==epoch)return;
 frame(`<header class="org-heading"><div><span class="org-kicker">${esc(ctx.school.name)}</span><h1>${esc(klass.name)}</h1></div><button class="org-button" id="refresh">Refresh results</button></header>${help(manager)}${manager?`<section class="org-panel"><h2>Class link</h2><a class="class-link" href="${esc(location.href)}">${esc(location.href)}</a><p class="panel-note">Share this with enrolled students. Signing in checks access; the link never grants it.</p></section><section class="org-panel"><h2>Class roster</h2><p class="panel-note">Up to 500 students. Use existing active school-student UIDs and fictional labels.</p>${roster.map(r=>`<p>${esc(r.label)} <small>${esc(r.id)}</small> <button class="org-button" data-remove="${esc(r.id)}">Remove from class</button></p>`).join('')||'<p>No students enrolled.</p>'}<form id="enroll" class="class-form"><label>Student UID<input name="uid" pattern="[A-Za-z0-9_-]{1,128}" required></label><label>Display label<input name="label" maxlength="80" required></label><p role="alert"></p><button type="submit" class="org-button">Add to class</button></form><p id="roster-message" role="alert"></p></section><section class="org-panel"><h2>Assign practice</h2><form id="assignment" class="class-form"><label>Assignment title<input name="title" maxlength="80" required></label><label>Due date<input name="due" type="date" required></label><label>Instructions<textarea name="instructions" maxlength="500" rows="3"></textarea></label><label>Unit<select id="unit">${course.map((u,i)=>`<option value="${i}">${esc(u.name)}</option>`).join('')}</select></label><div class="class-actions"><button type="button" class="org-button" id="select-unit">Select available figures</button><button type="button" class="org-button" id="clear-unit">Clear this unit</button></div><fieldset id="figures"></fieldset><p id="selected-count" role="status"></p><p class="panel-note">Selections persist when switching units. Missing and premium figures are excluded. All enrolled students can access saved assignments, including students added later. Due dates are reminders and do not block late practice.</p><p role="alert"></p><button type="submit" class="org-button org-primary">Save assignment</button></form></section>`:''}<section class="org-panel"><h2>Assignments</h2><p class="panel-note">Showing up to 100. Reports record first saved completions and app support; outside help is unknown.</p>${assignments.map(a=>`<article class="org-panel"><h3>${esc(a.title)}</h3><p>Due ${esc(a.due)} · ${a.lessonIds.length} figures</p><p>${esc(a.instructions)}</p>${manager?`<button class="org-button" data-report="${esc(a.id)}">Review results</button><div id="report-${esc(a.id)}"></div>`:`<a class="org-button org-primary" href="../?schoolHomework=${encodeURIComponent(a.id)}&school=${encodeURIComponent(s)}&class=${encodeURIComponent(c)}">Open homework</a>`}</article>`).join('')||'<p>No assignments yet.</p>'}</section>`);
 document.querySelector('#refresh').onclick=load;
 if(manager){
 formAction(document.querySelector('#enroll'),async f=>{await api.classroom.enroll(s,c,f.get('uid').trim(),f.get('label'));await load();});
 app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api.classroom.unenroll(s,c,b.dataset.remove);await load();}catch(e){document.querySelector('#roster-message').textContent=err(e);b.disabled=false;}});
 const selected=new Set(),unit=document.querySelector('#unit');const available=()=>course[Number(unit.value)].lessons.filter(l=>l.available&&!l.premium&&l.questions?.length);
 const draw=()=>{document.querySelector('#figures').innerHTML=`<legend>Figures in this unit</legend>${available().map(l=>`<label class="lesson-choice"><input type="checkbox" value="${l.id}" ${selected.has(l.id)?'checked':''}>Figure ${l.id}: ${esc(l.title)}</label>`).join('')||'<p>No available figures in this unit.</p>'}`;document.querySelector('#selected-count').textContent=selected.size+' figures selected across all units';document.querySelectorAll('#figures input').forEach(i=>i.onchange=()=>{i.checked?selected.add(Number(i.value)):selected.delete(Number(i.value));document.querySelector('#selected-count').textContent=selected.size+' figures selected across all units';});};unit.onchange=draw;document.querySelector('#select-unit').onclick=()=>{available().forEach(l=>selected.add(l.id));draw();};document.querySelector('#clear-unit').onclick=()=>{available().forEach(l=>selected.delete(l.id));draw();};draw();
 formAction(document.querySelector('#assignment'),async f=>{if(!selected.size)throw Error('Select at least one available figure.');await api.classroom.createAssignment(s,c,{title:f.get('title').trim(),instructions:f.get('instructions').trim(),due:f.get('due'),lessonIds:[...selected].sort((a,b)=>a-b)});await load();});
 app.querySelectorAll('[data-report]').forEach(b=>b.onclick=async()=>{b.disabled=true;const el=document.getElementById('report-'+b.dataset.report);try{const rows=await api.classroom.results(s,c,b.dataset.report,true);if(token!==epoch)return;const a=assignments.find(x=>x.id===b.dataset.report),people=[...roster,...[...new Set(rows.map(r=>r.uid))].filter(uid=>!roster.some(p=>p.id===uid)).map(id=>({id,label:'Former class member'}))];el.innerHTML=`<p class="panel-note">${rows.length>=1000?'Result limit reached. This report may be incomplete.':'First saved completion per figure. Refresh to load new work.'}</p>${people.map(person=>{const results=rows.filter(r=>r.uid===person.id),n=results.length,total=results.reduce((n,r)=>n+r.questions,0),correct=results.reduce((n,r)=>n+r.firstTry,0),support=results.reduce((n,r)=>n+r.supportSteps,0);return `<article><h4>${esc(person.label)}</h4><p>${n}/${a.lessonIds.length} figures · ${n===a.lessonIds.length?(support?'Completed with support':'Completed · No app support recorded'):'In progress'}</p><p>${total?Math.round(correct/total*100)+'% first-try answers':'No answers saved'} · ${support} steps with app support</p></article>`}).join('')||'<p>No students or results yet.</p>'}<p class="panel-note">These are client-reported homework records, not verified independent assessments. Removing a student from the class retains their saved results.</p>`;}catch(e){el.textContent=err(e);}finally{b.disabled=false;}});
 }
 }catch(e){if(token!==epoch)return;frame(`<section class="org-panel"><h1>Unable to open classes</h1><p>${esc(err(e))}</p><button class="org-button" id="retry">Try again</button></section>`);document.querySelector('#retry').onclick=load;}}
api.observe(u=>{epoch++;user=u;if(!valid(s)||(c&&!valid(c))){app.innerHTML='<p>Open the school or class link supplied by your administrator.</p>';return;}if(!u)login();else load();});
