import * as api from '../owner/client.js?v=f267d0fc61ae';
const app=document.querySelector('#join-app'),token=new URLSearchParams(location.search).get('invite');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let invitation,user,mode='register',busy=false;
const brand='<a class="org-brand" href="../"><img src="../assets/brand-transparent.png" alt=""><span>Reckoning Figures<small>YOUR NEXT CHAPTER</small></span></a>';
const classURL=()=>`classroom.html?school=${encodeURIComponent(invitation.schoolId)}&class=${encodeURIComponent(invitation.classId)}`;
function frame(body){app.innerHTML=`<div class="join-shell">${brand}<section class="org-panel">${body}</section></div>`;}
const message=e=>e.code==='auth/email-already-in-use'?'An account already exists with this email. Choose Sign in.':e.code==='auth/weak-password'?'Choose a password with at least 6 characters.':e.code?.startsWith('auth/')?'Could not sign in. Check your details and try again.':e.code==='permission-denied'?'Joining is unavailable. The school may be out of seats, its license may be inactive, or the join rules may need activation. Ask your teacher for help.':e.message||'Could not connect. Please try again.';
function status(r){if(r.state==='admitted'){location.replace(classURL());return;}frame(`<span class="staff-badge">${esc(invitation.schoolName)}</span><h1 class="join-title">${r.state==='pending'?'You’re on the list.':'Check with your teacher.'}</h1><p class="join-meta">${r.state==='pending'?`Your request to join ${esc(invitation.className)} is waiting for your teacher’s approval. Keep this link to check back.`:'Your request was declined. Your teacher can help with the next step.'}</p><button class="org-button org-primary" id="check-status">Check status</button><button class="org-button" id="signout">Sign out</button>`);document.querySelector('#check-status').onclick=load;document.querySelector('#signout').onclick=()=>api.logout();}
async function join(label){const result=await api.invitations.join(token,label);status(result);}
function render(){const active=invitation.active&&(!invitation.expiresAt||invitation.expiresAt.toMillis()>Date.now());if(!active){frame('<h1 class="join-title">A fresh link, please.</h1><p class="join-meta">This invitation has expired or been turned off. Ask your teacher for a new one.</p>');return;}
frame(`<span class="staff-badge">${esc(invitation.schoolName)}</span><h1 class="join-title">${esc(invitation.className)}</h1><p class="join-meta">${invitation.mode==='automatic'?'Your class is one step away.':'Create your account and request a place in this class.'}</p>${!user?`<div class="staff-tabs" role="tablist" aria-label="Account"><button role="tab" aria-selected="${mode==='register'}" data-mode="register">New account</button><button role="tab" aria-selected="${mode==='login'}" data-mode="login">Sign in</button></div>`:`<p class="staff-subtle">Signed in as ${esc(user.email||'your account')}.</p>`}<form class="staff-form" id="join-form"><label>Name<input name="label" autocomplete="nickname" maxlength="80" required placeholder="Name" value="${esc(user?.displayName||'')}"></label>${!user?'<label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="'+(mode==='register'?'new-password':'current-password')+'" minlength="6" required></label>':''}<p class="staff-error" role="alert" id="join-error"></p><button class="org-button org-primary" type="submit">${user?(invitation.mode==='automatic'?'Join class':'Request to join'):mode==='register'?'Create account & join':'Sign in & join'}</button>${!user?'<button type="button" class="org-button" id="google">Continue with Google</button>':'<button type="button" class="org-button" id="signout">Use another account</button>'}<p class="panel-note">${invitation.mode==='automatic'?'You’ll be enrolled automatically if the school has a seat available.':'Your teacher approves requests before you enter the class.'} Name and practice results will be visible to your school’s authorized staff.</p></form>`);
app.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});
const form=document.querySelector('#join-form');
async function run(fn){busy=true;form.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){const el=document.querySelector('#join-error');if(el)el.textContent=message(e);}finally{busy=false;form.querySelectorAll('button').forEach(b=>b.disabled=false);}}
form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);run(async()=>{if(!user){const result=await(mode==='register'?api.register(f.get('email').trim(),f.get('password')):api.login(f.get('email').trim(),f.get('password')));user=result.user;}await join(f.get('label').trim());});};
document.querySelector('#google')?.addEventListener('click',()=>{const name=form.elements.label;if(!name.reportValidity())return;run(async()=>{const result=await api.googleLogin();user=result.user;await join(name.value.trim());});});document.querySelector('#signout')?.addEventListener('click',()=>api.logout());}
async function load(){try{invitation=await api.invitations.get(token);if(!invitation.active||(invitation.expiresAt&&invitation.expiresAt.toMillis()<=Date.now())){render();return;}if(user){const r=await api.invitations.request(token);if(r){status(r);return;}}render();}catch(e){frame(`<h1 class="join-title">Let’s check that link.</h1><p class="join-meta">${esc(message(e))}</p><button class="org-button" id="retry">Try again</button>`);document.querySelector('#retry').onclick=load;}}
api.observe(u=>{user=u;if(!busy)load();});
