import * as api from '../owner/client.js?v=0842e0954dba';
const app=document.querySelector('#join-app'),token=new URLSearchParams(location.search).get('invite');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user,invitation,mode='register',busy=false,name='',epoch=0;
const brand='<a class="org-brand" href="../"><img src="../assets/brand-transparent.png" alt=""><span>Reckoning Figures<small>STAFF INVITATION</small></span></a>';
function frame(body){app.innerHTML=`<div class="join-shell">${brand}<section class="org-panel">${body}<p class="staff-error" id="error" role="alert"></p></section></div>`;}
const message=e=>e.code==='permission-denied'?'This account cannot use this invitation. Sign in with the exact email address invited. The invitation or school access may also need an administrator’s help.':e.code==='auth/email-already-in-use'?'This email already has an account. Choose Sign in.':e.code?.startsWith('auth/')?'Could not complete that step. Check your details and try again.':e.message||'Could not connect. Try again.';
async function run(fn){if(busy)return;busy=true;app.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){document.querySelector('#error').textContent=message(e);}finally{busy=false;app.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function account(){frame(`<h1 class="join-title">Your school awaits.</h1><p class="join-meta">Use the email address your administrator invited. We’ll check your invitation after sign-in.</p><div class="staff-tabs" role="tablist" aria-label="Account"><button role="tab" aria-selected="${mode==='register'}" data-mode="register">New account</button><button role="tab" aria-selected="${mode==='login'}" data-mode="login">Sign in</button></div><form class="staff-form" id="auth"><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required minlength="6" autocomplete="${mode==='register'?'new-password':'current-password'}"></label><button class="org-button org-primary">${mode==='register'?'Create account':'Sign in'}</button><button class="org-button" type="button" id="google">Continue with Google</button></form>`);app.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;account();});document.querySelector('#auth').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);run(async()=>{const r=await (mode==='register'?api.register:api.login)(f.get('email').trim(),f.get('password'));user=r.user;await load();});};document.querySelector('#google').onclick=()=>run(async()=>{user=(await api.googleLogin()).user;await load();});}
function signout(){document.querySelector('#signout')?.addEventListener('click',()=>run(async()=>{await api.logout();user=null;invitation=null;name='';account();}));}
function render(){const i=invitation;if(i.state==='accepted'){frame(`<h1 class="join-title">Invitation accepted.</h1><p class="join-meta">Your school manages your current access.</p><a class="org-button org-primary" href="./?school=${encodeURIComponent(i.schoolId)}">Open school</a><button id="signout" class="org-button">Use another account</button>`);signout();return;}
 if(i.state!=='pending'||i.expiresAt.toMillis()<=Date.now()){frame('<h1 class="join-title">A fresh link, please.</h1><p class="join-meta">This invitation has expired or been turned off. Ask your administrator for a new link.</p><button id="signout" class="org-button">Use another account</button>');signout();return;}
 if(!user.emailVerified){frame(`<span class="staff-badge">${esc(i.schoolName)}</span><h1 class="join-title">Verify your email.</h1><p class="join-meta">Confirm ${esc(user.email)} before joining as ${esc(i.role)}. Open the verification email, then return here.</p><div class="staff-actions"><button id="verify" class="org-button org-primary">Send verification email</button><button id="refresh-identity" class="org-button">I’ve verified my email</button><button id="signout" class="org-button">Use another account</button></div><p id="verification-status" role="status"></p>`);document.querySelector('#verify').onclick=()=>run(async()=>{await api.verifyEmail();document.querySelector('#verification-status').textContent='Verification email sent. Check your inbox and spam folder.';});document.querySelector('#refresh-identity').onclick=()=>run(async()=>{user=await api.refreshIdentity();if(user.emailVerified)await load();else document.querySelector('#verification-status').textContent='Not verified yet. Open the email link first, then try again.';});signout();return;}
 frame(`<span class="staff-badge">${esc(i.schoolName)}</span><h1 class="join-title">Welcome to your workspace.</h1><p class="join-meta">You’re joining as ${esc(i.role)} with ${esc(user.email)}.</p><form id="accept" class="staff-form"><label>Name<input name="label" required maxlength="80" autocomplete="name" placeholder="Name" value="${esc(name||user.displayName||'')}"></label><button class="org-button org-primary">Join school</button><button type="button" id="signout" class="org-button">Use another account</button></form>`);document.querySelector('#accept').onsubmit=e=>{e.preventDefault();name=new FormData(e.target).get('label').trim();run(async()=>{const s=await api.staffInvitations.accept(token,name);location.replace(`./?school=${encodeURIComponent(s)}`);});};signout();}
async function load(){const version=++epoch;try{const i=await api.staffInvitations.get(token);if(version!==epoch)return;invitation=i;render();}catch(e){if(version!==epoch)return;frame(`<h1 class="join-title">Let’s check your invitation.</h1><p class="join-meta">${esc(message(e))}</p><button class="org-button org-primary" id="retry">Try again</button><button class="org-button" id="signout">Use another account</button>`);document.querySelector('#retry').onclick=()=>run(load);signout();}}
api.observe(u=>{user=u;if(busy)return;epoch++;if(u)load();else account();});
